### ISSUE TITLE
Can't block https://www.letao.com.tw

### ISSUE THREAD

**Issue by StrongerLiu** [femioladeji/screentime#18]
ScreenTime can't block "https://www.letao.com.tw". Could you help me? Thanks!

**Comment by femioladeji** [comment]
@StrongerLiu I'll look into this and get back to you

**Comment by femioladeji** [comment]
@StrongerLiu thanks for reporting this. I've released a new version. v5.0.1. It's currently being reviewed by chrome store. The extension will be updated once it passes the review.

**Comment by StrongerLiu** [comment]
Thanks for your help!
