### ISSUE TITLE
Enable all feature

### ISSUE THREAD

**Issue by eenlars** [femioladeji/screentime#22]
Hi, Amazing work! I like the extension.

Would it be possible to create a button to enable blocking all websites? Now, the disable button is not a toggle, rather it switches off all.

**Comment by femioladeji** [comment]
@eenlars it should have been a toggle button. If everything is disabled, it should switch to "Enable all". I'll work on a fix

**Comment by femioladeji** [comment]
@eenlars I've fixed the bug in this PR #23 and a new version has been submitted to the Chromestore. Once it is approved, the extension will be automatically updated

**Comment by eenlars** [comment]
@femioladeji Great thanks, it works again!
