### ISSUE TITLE
[Bug] Advanced setting doesn't save

### ISSUE THREAD

**Issue by jameszhang-a** [femioladeji/screentime#27]
For each of the websites, I select the days in the advanced section, enter the time, and hit save. But as soon as I click out and back into the extension again, the settings are reset. So when I go back and click on the gear for a site, none of the days are selected again. 

I made sure to wait until the saving animation is finished before exiting.

**Comment by femioladeji** [comment]
Thanks for creating this issue. I'll look into it and get back to you

**Comment by jameszhang-a** [comment]
Thank you. In case you need this information:

**Browser**: Version 98.0.4758.109 (Official Build) (arm64)
**OS**: Apple M1 Pro. Monterey 12.1

**Comment by femioladeji** [comment]
I couldn't replicate the bug, I've attached a video of what I tried.

Did you ensure that the start time is greater than or equal to `00:00` and the end time is less than or equal to `23:59` also the end time has to be greater than the start time

https://user-images.githubusercontent.com/17332992/158029384-30d40dc3-6f3d-49a2-8e3c-5ce085e6950b.mov
