### ISSUE TITLE
Support Microsoft Edge

### ISSUE THREAD

**Issue by kozuch** [femioladeji/screentime#45]
Hi, any chance this project could support Microsoft Edge since it is also based on Chromium? Thanks!

**Comment by femioladeji** [comment]
@kozuch yes we are currently looking into that

**Comment by femioladeji** [comment]
@kozuch here's the link to the extension for Microsoft Edge https://microsoftedge.microsoft.com/addons/detail/screentime/lbfgleljamdojggebmbakgjhajkjelck
